use winit::keyboard;

#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
pub enum KeyCode {
    Backquote,
    Backslash,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,
    AltLeft,
    AltRight,
    Backspace,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    SuperLeft,
    SuperRight,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    Convert,
    KanaMode,
    Lang1,
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    NonConvert,
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,
    NumpadSubtract,
    Escape,
    Fn,
    FnLock,
    PrintScreen,
    ScrollLock,
    Pause,
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,
    Meta,
    Hyper,
    Turbo,
    Abort,
    Resume,
    Suspend,
    Again,
    Copy,
    Cut,
    Find,
    Open,
    Paste,
    Props,
    Select,
    Undo,
    Hiragana,
    Katakana,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,
}
impl KeyCode {
    pub fn from_winit(key: winit::keyboard::KeyCode) -> Option<KeyCode> {
        match key {
            keyboard::KeyCode::Backquote => Some(KeyCode::Backquote),
            keyboard::KeyCode::Backslash => Some(KeyCode::Backslash),
            keyboard::KeyCode::BracketLeft => Some(KeyCode::BracketLeft),
            keyboard::KeyCode::BracketRight => Some(KeyCode::BracketRight),
            keyboard::KeyCode::Comma => Some(KeyCode::Comma),
            keyboard::KeyCode::Digit0 => Some(KeyCode::Digit0),
            keyboard::KeyCode::Digit1 => Some(KeyCode::Digit1),
            keyboard::KeyCode::Digit2 => Some(KeyCode::Digit2),
            keyboard::KeyCode::Digit3 => Some(KeyCode::Digit3),
            keyboard::KeyCode::Digit4 => Some(KeyCode::Digit4),
            keyboard::KeyCode::Digit5 => Some(KeyCode::Digit5),
            keyboard::KeyCode::Digit6 => Some(KeyCode::Digit6),
            keyboard::KeyCode::Digit7 => Some(KeyCode::Digit7),
            keyboard::KeyCode::Digit8 => Some(KeyCode::Digit8),
            keyboard::KeyCode::Digit9 => Some(KeyCode::Digit9),
            keyboard::KeyCode::Equal => Some(KeyCode::Equal),
            keyboard::KeyCode::IntlBackslash => Some(KeyCode::IntlBackslash),
            keyboard::KeyCode::IntlRo => Some(KeyCode::IntlRo),
            keyboard::KeyCode::IntlYen => Some(KeyCode::IntlYen),
            keyboard::KeyCode::KeyA => Some(KeyCode::KeyA),
            keyboard::KeyCode::KeyB => Some(KeyCode::KeyB),
            keyboard::KeyCode::KeyC => Some(KeyCode::KeyC),
            keyboard::KeyCode::KeyD => Some(KeyCode::KeyD),
            keyboard::KeyCode::KeyE => Some(KeyCode::KeyE),
            keyboard::KeyCode::KeyF => Some(KeyCode::KeyF),
            keyboard::KeyCode::KeyG => Some(KeyCode::KeyG),
            keyboard::KeyCode::KeyH => Some(KeyCode::KeyH),
            keyboard::KeyCode::KeyI => Some(KeyCode::KeyI),
            keyboard::KeyCode::KeyJ => Some(KeyCode::KeyJ),
            keyboard::KeyCode::KeyK => Some(KeyCode::KeyK),
            keyboard::KeyCode::KeyL => Some(KeyCode::KeyL),
            keyboard::KeyCode::KeyM => Some(KeyCode::KeyM),
            keyboard::KeyCode::KeyN => Some(KeyCode::KeyN),
            keyboard::KeyCode::KeyO => Some(KeyCode::KeyO),
            keyboard::KeyCode::KeyP => Some(KeyCode::KeyP),
            keyboard::KeyCode::KeyQ => Some(KeyCode::KeyQ),
            keyboard::KeyCode::KeyR => Some(KeyCode::KeyR),
            keyboard::KeyCode::KeyS => Some(KeyCode::KeyS),
            keyboard::KeyCode::KeyT => Some(KeyCode::KeyT),
            keyboard::KeyCode::KeyU => Some(KeyCode::KeyU),
            keyboard::KeyCode::KeyV => Some(KeyCode::KeyV),
            keyboard::KeyCode::KeyW => Some(KeyCode::KeyW),
            keyboard::KeyCode::KeyX => Some(KeyCode::KeyX),
            keyboard::KeyCode::KeyY => Some(KeyCode::KeyY),
            keyboard::KeyCode::KeyZ => Some(KeyCode::KeyZ),
            keyboard::KeyCode::Minus => Some(KeyCode::Minus),
            keyboard::KeyCode::Period => Some(KeyCode::Period),
            keyboard::KeyCode::Quote => Some(KeyCode::Quote),
            keyboard::KeyCode::Semicolon => Some(KeyCode::Semicolon),
            keyboard::KeyCode::Slash => Some(KeyCode::Slash),
            keyboard::KeyCode::AltLeft => Some(KeyCode::AltLeft),
            keyboard::KeyCode::AltRight => Some(KeyCode::AltRight),
            keyboard::KeyCode::Backspace => Some(KeyCode::Backspace),
            keyboard::KeyCode::CapsLock => Some(KeyCode::CapsLock),
            keyboard::KeyCode::ContextMenu => Some(KeyCode::ContextMenu),
            keyboard::KeyCode::ControlLeft => Some(KeyCode::ControlLeft),
            keyboard::KeyCode::ControlRight => Some(KeyCode::ControlRight),
            keyboard::KeyCode::Enter => Some(KeyCode::Enter),
            keyboard::KeyCode::SuperLeft => Some(KeyCode::SuperLeft),
            keyboard::KeyCode::SuperRight => Some(KeyCode::SuperRight),
            keyboard::KeyCode::ShiftLeft => Some(KeyCode::ShiftLeft),
            keyboard::KeyCode::ShiftRight => Some(KeyCode::ShiftRight),
            keyboard::KeyCode::Space => Some(KeyCode::Space),
            keyboard::KeyCode::Tab => Some(KeyCode::Tab),
            keyboard::KeyCode::Convert => Some(KeyCode::Convert),
            keyboard::KeyCode::KanaMode => Some(KeyCode::KanaMode),
            keyboard::KeyCode::Lang1 => Some(KeyCode::Lang1),
            keyboard::KeyCode::Lang2 => Some(KeyCode::Lang2),
            keyboard::KeyCode::Lang3 => Some(KeyCode::Lang3),
            keyboard::KeyCode::Lang4 => Some(KeyCode::Lang4),
            keyboard::KeyCode::Lang5 => Some(KeyCode::Lang5),
            keyboard::KeyCode::NonConvert => Some(KeyCode::NonConvert),
            keyboard::KeyCode::Delete => Some(KeyCode::Delete),
            keyboard::KeyCode::End => Some(KeyCode::End),
            keyboard::KeyCode::Help => Some(KeyCode::Help),
            keyboard::KeyCode::Home => Some(KeyCode::Home),
            keyboard::KeyCode::Insert => Some(KeyCode::Insert),
            keyboard::KeyCode::PageDown => Some(KeyCode::PageDown),
            keyboard::KeyCode::PageUp => Some(KeyCode::PageUp),
            keyboard::KeyCode::ArrowDown => Some(KeyCode::ArrowDown),
            keyboard::KeyCode::ArrowLeft => Some(KeyCode::ArrowLeft),
            keyboard::KeyCode::ArrowRight => Some(KeyCode::ArrowRight),
            keyboard::KeyCode::ArrowUp => Some(KeyCode::ArrowUp),
            keyboard::KeyCode::NumLock => Some(KeyCode::NumLock),
            keyboard::KeyCode::Numpad0 => Some(KeyCode::Numpad0),
            keyboard::KeyCode::Numpad1 => Some(KeyCode::Numpad1),
            keyboard::KeyCode::Numpad2 => Some(KeyCode::Numpad2),
            keyboard::KeyCode::Numpad3 => Some(KeyCode::Numpad3),
            keyboard::KeyCode::Numpad4 => Some(KeyCode::Numpad4),
            keyboard::KeyCode::Numpad5 => Some(KeyCode::Numpad5),
            keyboard::KeyCode::Numpad6 => Some(KeyCode::Numpad6),
            keyboard::KeyCode::Numpad7 => Some(KeyCode::Numpad7),
            keyboard::KeyCode::Numpad8 => Some(KeyCode::Numpad8),
            keyboard::KeyCode::Numpad9 => Some(KeyCode::Numpad9),
            keyboard::KeyCode::NumpadAdd => Some(KeyCode::NumpadAdd),
            keyboard::KeyCode::NumpadBackspace => Some(KeyCode::NumpadBackspace),
            keyboard::KeyCode::NumpadClear => Some(KeyCode::NumpadClear),
            keyboard::KeyCode::NumpadClearEntry => Some(KeyCode::NumpadClearEntry),
            keyboard::KeyCode::NumpadComma => Some(KeyCode::NumpadComma),
            keyboard::KeyCode::NumpadDecimal => Some(KeyCode::NumpadDecimal),
            keyboard::KeyCode::NumpadDivide => Some(KeyCode::NumpadDivide),
            keyboard::KeyCode::NumpadEnter => Some(KeyCode::NumpadEnter),
            keyboard::KeyCode::NumpadEqual => Some(KeyCode::NumpadEqual),
            keyboard::KeyCode::NumpadHash => Some(KeyCode::NumpadHash),
            keyboard::KeyCode::NumpadMemoryAdd => Some(KeyCode::NumpadMemoryAdd),
            keyboard::KeyCode::NumpadMemoryClear => Some(KeyCode::NumpadMemoryClear),
            keyboard::KeyCode::NumpadMemoryRecall => Some(KeyCode::NumpadMemoryRecall),
            keyboard::KeyCode::NumpadMemoryStore => Some(KeyCode::NumpadMemoryStore),
            keyboard::KeyCode::NumpadMemorySubtract => Some(KeyCode::NumpadMemorySubtract),
            keyboard::KeyCode::NumpadMultiply => Some(KeyCode::NumpadMultiply),
            keyboard::KeyCode::NumpadParenLeft => Some(KeyCode::NumpadParenLeft),
            keyboard::KeyCode::NumpadParenRight => Some(KeyCode::NumpadParenRight),
            keyboard::KeyCode::NumpadStar => Some(KeyCode::NumpadStar),
            keyboard::KeyCode::NumpadSubtract => Some(KeyCode::NumpadSubtract),
            keyboard::KeyCode::Escape => Some(KeyCode::Escape),
            keyboard::KeyCode::Fn => Some(KeyCode::Fn),
            keyboard::KeyCode::FnLock => Some(KeyCode::FnLock),
            keyboard::KeyCode::PrintScreen => Some(KeyCode::PrintScreen),
            keyboard::KeyCode::ScrollLock => Some(KeyCode::ScrollLock),
            keyboard::KeyCode::Pause => Some(KeyCode::Pause),
            keyboard::KeyCode::BrowserBack => Some(KeyCode::BrowserBack),
            keyboard::KeyCode::BrowserFavorites => Some(KeyCode::BrowserFavorites),
            keyboard::KeyCode::BrowserForward => Some(KeyCode::BrowserForward),
            keyboard::KeyCode::BrowserHome => Some(KeyCode::BrowserHome),
            keyboard::KeyCode::BrowserRefresh => Some(KeyCode::BrowserRefresh),
            keyboard::KeyCode::BrowserSearch => Some(KeyCode::BrowserSearch),
            keyboard::KeyCode::BrowserStop => Some(KeyCode::BrowserStop),
            keyboard::KeyCode::Eject => Some(KeyCode::Eject),
            keyboard::KeyCode::LaunchApp1 => Some(KeyCode::LaunchApp1),
            keyboard::KeyCode::LaunchApp2 => Some(KeyCode::LaunchApp2),
            keyboard::KeyCode::LaunchMail => Some(KeyCode::LaunchMail),
            keyboard::KeyCode::MediaPlayPause => Some(KeyCode::MediaPlayPause),
            keyboard::KeyCode::MediaSelect => Some(KeyCode::MediaSelect),
            keyboard::KeyCode::MediaStop => Some(KeyCode::MediaStop),
            keyboard::KeyCode::MediaTrackNext => Some(KeyCode::MediaTrackNext),
            keyboard::KeyCode::MediaTrackPrevious => Some(KeyCode::MediaTrackPrevious),
            keyboard::KeyCode::Power => Some(KeyCode::Power),
            keyboard::KeyCode::Sleep => Some(KeyCode::Sleep),
            keyboard::KeyCode::AudioVolumeDown => Some(KeyCode::AudioVolumeDown),
            keyboard::KeyCode::AudioVolumeMute => Some(KeyCode::AudioVolumeMute),
            keyboard::KeyCode::AudioVolumeUp => Some(KeyCode::AudioVolumeUp),
            keyboard::KeyCode::WakeUp => Some(KeyCode::WakeUp),
            keyboard::KeyCode::Meta => Some(KeyCode::Meta),
            keyboard::KeyCode::Hyper => Some(KeyCode::Hyper),
            keyboard::KeyCode::Turbo => Some(KeyCode::Turbo),
            keyboard::KeyCode::Abort => Some(KeyCode::Abort),
            keyboard::KeyCode::Resume => Some(KeyCode::Resume),
            keyboard::KeyCode::Suspend => Some(KeyCode::Suspend),
            keyboard::KeyCode::Again => Some(KeyCode::Again),
            keyboard::KeyCode::Copy => Some(KeyCode::Copy),
            keyboard::KeyCode::Cut => Some(KeyCode::Cut),
            keyboard::KeyCode::Find => Some(KeyCode::Find),
            keyboard::KeyCode::Open => Some(KeyCode::Open),
            keyboard::KeyCode::Paste => Some(KeyCode::Paste),
            keyboard::KeyCode::Props => Some(KeyCode::Props),
            keyboard::KeyCode::Select => Some(KeyCode::Select),
            keyboard::KeyCode::Undo => Some(KeyCode::Undo),
            keyboard::KeyCode::Hiragana => Some(KeyCode::Hiragana),
            keyboard::KeyCode::Katakana => Some(KeyCode::Katakana),
            keyboard::KeyCode::F1 => Some(KeyCode::F1),
            keyboard::KeyCode::F2 => Some(KeyCode::F2),
            keyboard::KeyCode::F3 => Some(KeyCode::F3),
            keyboard::KeyCode::F4 => Some(KeyCode::F4),
            keyboard::KeyCode::F5 => Some(KeyCode::F5),
            keyboard::KeyCode::F6 => Some(KeyCode::F6),
            keyboard::KeyCode::F7 => Some(KeyCode::F7),
            keyboard::KeyCode::F8 => Some(KeyCode::F8),
            keyboard::KeyCode::F9 => Some(KeyCode::F9),
            keyboard::KeyCode::F10 => Some(KeyCode::F10),
            keyboard::KeyCode::F11 => Some(KeyCode::F11),
            keyboard::KeyCode::F12 => Some(KeyCode::F12),
            keyboard::KeyCode::F13 => Some(KeyCode::F13),
            keyboard::KeyCode::F14 => Some(KeyCode::F14),
            keyboard::KeyCode::F15 => Some(KeyCode::F15),
            keyboard::KeyCode::F16 => Some(KeyCode::F16),
            keyboard::KeyCode::F17 => Some(KeyCode::F17),
            keyboard::KeyCode::F18 => Some(KeyCode::F18),
            keyboard::KeyCode::F19 => Some(KeyCode::F19),
            keyboard::KeyCode::F20 => Some(KeyCode::F20),
            keyboard::KeyCode::F21 => Some(KeyCode::F21),
            keyboard::KeyCode::F22 => Some(KeyCode::F22),
            keyboard::KeyCode::F23 => Some(KeyCode::F23),
            keyboard::KeyCode::F24 => Some(KeyCode::F24),
            keyboard::KeyCode::F25 => Some(KeyCode::F25),
            keyboard::KeyCode::F26 => Some(KeyCode::F26),
            keyboard::KeyCode::F27 => Some(KeyCode::F27),
            keyboard::KeyCode::F28 => Some(KeyCode::F28),
            keyboard::KeyCode::F29 => Some(KeyCode::F29),
            keyboard::KeyCode::F30 => Some(KeyCode::F30),
            keyboard::KeyCode::F31 => Some(KeyCode::F31),
            keyboard::KeyCode::F32 => Some(KeyCode::F32),
            keyboard::KeyCode::F33 => Some(KeyCode::F33),
            keyboard::KeyCode::F34 => Some(KeyCode::F34),
            keyboard::KeyCode::F35 => Some(KeyCode::F35),
            _ => None
        }
    }
}