use winit::keyboard;

#[derive(Debug, Hash, Clone, Copy, serde::Serialize, serde::Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub enum KeyCode {
    Backquote,
    Backslash,
    BracketLeft,
    BracketRight,
    Comma,
    Digit0,
    Digit1,
    Digit2,
    Digit3,
    Digit4,
    Digit5,
    Digit6,
    Digit7,
    Digit8,
    Digit9,
    Equal,
    IntlBackslash,
    IntlRo,
    IntlYen,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
    Minus,
    Period,
    Quote,
    Semicolon,
    Slash,
    AltLeft,
    AltRight,
    Backspace,
    CapsLock,
    ContextMenu,
    ControlLeft,
    ControlRight,
    Enter,
    SuperLeft,
    SuperRight,
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    Convert,
    KanaMode,
    Lang1,
    Lang2,
    Lang3,
    Lang4,
    Lang5,
    NonConvert,
    Delete,
    End,
    Help,
    Home,
    Insert,
    PageDown,
    PageUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    NumLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadBackspace,
    NumpadClear,
    NumpadClearEntry,
    NumpadComma,
    NumpadDecimal,
    NumpadDivide,
    NumpadEnter,
    NumpadEqual,
    NumpadHash,
    NumpadMemoryAdd,
    NumpadMemoryClear,
    NumpadMemoryRecall,
    NumpadMemoryStore,
    NumpadMemorySubtract,
    NumpadMultiply,
    NumpadParenLeft,
    NumpadParenRight,
    NumpadStar,
    NumpadSubtract,
    Escape,
    Fn,
    FnLock,
    PrintScreen,
    ScrollLock,
    Pause,
    BrowserBack,
    BrowserFavorites,
    BrowserForward,
    BrowserHome,
    BrowserRefresh,
    BrowserSearch,
    BrowserStop,
    Eject,
    LaunchApp1,
    LaunchApp2,
    LaunchMail,
    MediaPlayPause,
    MediaSelect,
    MediaStop,
    MediaTrackNext,
    MediaTrackPrevious,
    Power,
    Sleep,
    AudioVolumeDown,
    AudioVolumeMute,
    AudioVolumeUp,
    WakeUp,
    Meta,
    Hyper,
    Turbo,
    Abort,
    Resume,
    Suspend,
    Again,
    Copy,
    Cut,
    Find,
    Open,
    Paste,
    Props,
    Select,
    Undo,
    Hiragana,
    Katakana,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,
}
impl KeyCode {
    pub fn from_winit(key: winit::keyboard::PhysicalKey) -> Option<KeyCode> {
        match key {
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Backquote) => Some(KeyCode::Backquote),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Backslash ) => Some(KeyCode::Backslash),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::BracketLeft ) => Some(KeyCode::BracketLeft),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::BracketRight ) => Some(KeyCode::BracketRight),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Comma ) => Some(KeyCode::Comma),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit0 ) => Some(KeyCode::Digit0),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit1 ) => Some(KeyCode::Digit1),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit2 ) => Some(KeyCode::Digit2),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit3 ) => Some(KeyCode::Digit3),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit4 ) => Some(KeyCode::Digit4),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit5 ) => Some(KeyCode::Digit5),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit6 ) => Some(KeyCode::Digit6),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit7 ) => Some(KeyCode::Digit7),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit8 ) => Some(KeyCode::Digit8),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Digit9 ) => Some(KeyCode::Digit9),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Equal ) => Some(KeyCode::Equal),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::IntlBackslash ) => Some(KeyCode::IntlBackslash),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::IntlRo ) => Some(KeyCode::IntlRo),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::IntlYen ) => Some(KeyCode::IntlYen),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyA ) => Some(KeyCode::KeyA),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyB ) => Some(KeyCode::KeyB),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyC ) => Some(KeyCode::KeyC),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyD ) => Some(KeyCode::KeyD),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyE ) => Some(KeyCode::KeyE),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyF ) => Some(KeyCode::KeyF),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyG ) => Some(KeyCode::KeyG),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyH ) => Some(KeyCode::KeyH),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyI ) => Some(KeyCode::KeyI),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyJ ) => Some(KeyCode::KeyJ),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyK ) => Some(KeyCode::KeyK),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyL ) => Some(KeyCode::KeyL),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyM ) => Some(KeyCode::KeyM),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyN ) => Some(KeyCode::KeyN),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyO ) => Some(KeyCode::KeyO),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyP ) => Some(KeyCode::KeyP),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyQ ) => Some(KeyCode::KeyQ),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyR ) => Some(KeyCode::KeyR),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyS ) => Some(KeyCode::KeyS),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyT ) => Some(KeyCode::KeyT),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyU ) => Some(KeyCode::KeyU),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyV ) => Some(KeyCode::KeyV),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyW ) => Some(KeyCode::KeyW),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyX ) => Some(KeyCode::KeyX),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyY ) => Some(KeyCode::KeyY),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KeyZ ) => Some(KeyCode::KeyZ),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Minus ) => Some(KeyCode::Minus),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Period ) => Some(KeyCode::Period),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Quote ) => Some(KeyCode::Quote),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Semicolon ) => Some(KeyCode::Semicolon),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Slash ) => Some(KeyCode::Slash),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::AltLeft ) => Some(KeyCode::AltLeft),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::AltRight ) => Some(KeyCode::AltRight),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Backspace ) => Some(KeyCode::Backspace),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::CapsLock ) => Some(KeyCode::CapsLock),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ContextMenu ) => Some(KeyCode::ContextMenu),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ControlLeft ) => Some(KeyCode::ControlLeft),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ControlRight ) => Some(KeyCode::ControlRight),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Enter ) => Some(KeyCode::Enter),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::SuperLeft ) => Some(KeyCode::SuperLeft),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::SuperRight ) => Some(KeyCode::SuperRight),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ShiftLeft ) => Some(KeyCode::ShiftLeft),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ShiftRight ) => Some(KeyCode::ShiftRight),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Space ) => Some(KeyCode::Space),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Tab ) => Some(KeyCode::Tab),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Convert ) => Some(KeyCode::Convert),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::KanaMode ) => Some(KeyCode::KanaMode),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Lang1 ) => Some(KeyCode::Lang1),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Lang2 ) => Some(KeyCode::Lang2),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Lang3 ) => Some(KeyCode::Lang3),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Lang4 ) => Some(KeyCode::Lang4),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Lang5 ) => Some(KeyCode::Lang5),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NonConvert ) => Some(KeyCode::NonConvert),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Delete ) => Some(KeyCode::Delete),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::End ) => Some(KeyCode::End),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Help ) => Some(KeyCode::Help),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Home ) => Some(KeyCode::Home),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Insert ) => Some(KeyCode::Insert),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::PageDown ) => Some(KeyCode::PageDown),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::PageUp ) => Some(KeyCode::PageUp),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ArrowDown ) => Some(KeyCode::ArrowDown),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ArrowLeft ) => Some(KeyCode::ArrowLeft),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ArrowRight ) => Some(KeyCode::ArrowRight),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ArrowUp ) => Some(KeyCode::ArrowUp),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumLock ) => Some(KeyCode::NumLock),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad0 ) => Some(KeyCode::Numpad0),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad1 ) => Some(KeyCode::Numpad1),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad2 ) => Some(KeyCode::Numpad2),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad3 ) => Some(KeyCode::Numpad3),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad4 ) => Some(KeyCode::Numpad4),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad5 ) => Some(KeyCode::Numpad5),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad6 ) => Some(KeyCode::Numpad6),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad7 ) => Some(KeyCode::Numpad7),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad8 ) => Some(KeyCode::Numpad8),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Numpad9 ) => Some(KeyCode::Numpad9),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadAdd ) => Some(KeyCode::NumpadAdd),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadBackspace ) => Some(KeyCode::NumpadBackspace),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadClear ) => Some(KeyCode::NumpadClear),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadClearEntry ) => Some(KeyCode::NumpadClearEntry),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadComma ) => Some(KeyCode::NumpadComma),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadDecimal ) => Some(KeyCode::NumpadDecimal),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadDivide ) => Some(KeyCode::NumpadDivide),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadEnter ) => Some(KeyCode::NumpadEnter),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadEqual ) => Some(KeyCode::NumpadEqual),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadHash ) => Some(KeyCode::NumpadHash),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadMemoryAdd ) => Some(KeyCode::NumpadMemoryAdd),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadMemoryClear ) => Some(KeyCode::NumpadMemoryClear),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadMemoryRecall ) => Some(KeyCode::NumpadMemoryRecall),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadMemoryStore ) => Some(KeyCode::NumpadMemoryStore),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadMemorySubtract ) => Some(KeyCode::NumpadMemorySubtract),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadMultiply ) => Some(KeyCode::NumpadMultiply),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadParenLeft ) => Some(KeyCode::NumpadParenLeft),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadParenRight ) => Some(KeyCode::NumpadParenRight),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadStar ) => Some(KeyCode::NumpadStar),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::NumpadSubtract ) => Some(KeyCode::NumpadSubtract),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Escape ) => Some(KeyCode::Escape),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Fn ) => Some(KeyCode::Fn),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::FnLock ) => Some(KeyCode::FnLock),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::PrintScreen ) => Some(KeyCode::PrintScreen),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::ScrollLock ) => Some(KeyCode::ScrollLock),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Pause ) => Some(KeyCode::Pause),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::BrowserBack ) => Some(KeyCode::BrowserBack),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::BrowserFavorites ) => Some(KeyCode::BrowserFavorites),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::BrowserForward ) => Some(KeyCode::BrowserForward),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::BrowserHome ) => Some(KeyCode::BrowserHome),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::BrowserRefresh ) => Some(KeyCode::BrowserRefresh),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::BrowserSearch ) => Some(KeyCode::BrowserSearch),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::BrowserStop ) => Some(KeyCode::BrowserStop),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Eject ) => Some(KeyCode::Eject),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::LaunchApp1 ) => Some(KeyCode::LaunchApp1),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::LaunchApp2 ) => Some(KeyCode::LaunchApp2),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::LaunchMail ) => Some(KeyCode::LaunchMail),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::MediaPlayPause ) => Some(KeyCode::MediaPlayPause),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::MediaSelect ) => Some(KeyCode::MediaSelect),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::MediaStop ) => Some(KeyCode::MediaStop),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::MediaTrackNext ) => Some(KeyCode::MediaTrackNext),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::MediaTrackPrevious ) => Some(KeyCode::MediaTrackPrevious),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Power ) => Some(KeyCode::Power),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Sleep ) => Some(KeyCode::Sleep),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::AudioVolumeDown ) => Some(KeyCode::AudioVolumeDown),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::AudioVolumeMute ) => Some(KeyCode::AudioVolumeMute),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::AudioVolumeUp ) => Some(KeyCode::AudioVolumeUp),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::WakeUp ) => Some(KeyCode::WakeUp),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Meta ) => Some(KeyCode::Meta),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Hyper ) => Some(KeyCode::Hyper),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Turbo ) => Some(KeyCode::Turbo),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Abort ) => Some(KeyCode::Abort),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Resume ) => Some(KeyCode::Resume),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Suspend ) => Some(KeyCode::Suspend),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Again ) => Some(KeyCode::Again),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Copy ) => Some(KeyCode::Copy),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Cut ) => Some(KeyCode::Cut),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Find ) => Some(KeyCode::Find),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Open ) => Some(KeyCode::Open),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Paste ) => Some(KeyCode::Paste),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Props ) => Some(KeyCode::Props),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Select ) => Some(KeyCode::Select),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Undo ) => Some(KeyCode::Undo),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Hiragana ) => Some(KeyCode::Hiragana),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::Katakana ) => Some(KeyCode::Katakana),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F1 ) => Some(KeyCode::F1),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F2 ) => Some(KeyCode::F2),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F3 ) => Some(KeyCode::F3),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F4 ) => Some(KeyCode::F4),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F5 ) => Some(KeyCode::F5),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F6 ) => Some(KeyCode::F6),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F7 ) => Some(KeyCode::F7),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F8 ) => Some(KeyCode::F8),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F9 ) => Some(KeyCode::F9),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F10 ) => Some(KeyCode::F10),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F11 ) => Some(KeyCode::F11),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F12 ) => Some(KeyCode::F12),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F13 ) => Some(KeyCode::F13),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F14 ) => Some(KeyCode::F14),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F15 ) => Some(KeyCode::F15),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F16 ) => Some(KeyCode::F16),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F17 ) => Some(KeyCode::F17),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F18 ) => Some(KeyCode::F18),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F19 ) => Some(KeyCode::F19),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F20 ) => Some(KeyCode::F20),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F21 ) => Some(KeyCode::F21),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F22 ) => Some(KeyCode::F22),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F23 ) => Some(KeyCode::F23),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F24 ) => Some(KeyCode::F24),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F25 ) => Some(KeyCode::F25),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F26 ) => Some(KeyCode::F26),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F27 ) => Some(KeyCode::F27),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F28 ) => Some(KeyCode::F28),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F29 ) => Some(KeyCode::F29),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F30 ) => Some(KeyCode::F30),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F31 ) => Some(KeyCode::F31),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F32 ) => Some(KeyCode::F32),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F33 ) => Some(KeyCode::F33),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F34 ) => Some(KeyCode::F34),
            keyboard::PhysicalKey::Code(winit::keyboard::KeyCode::F35 ) => Some(KeyCode::F35),
            keyboard::PhysicalKey::Code(_) => None,
            keyboard::PhysicalKey::Unidentified(native_code) => { 
                println!("unidentified keystroke native code"); 
                None
            },
        }
    }
}